### PR TITLE
Fixing U120 operations and divison by 0

### LINKED ISSUE #119: OP2 behaviour on overflow
The current code for evaluating arithmetic OP2 operations is as follows:

```
              ADD => a_u.wrapping_add(b_u) & NUM_MASK,
              SUB => a_u.wrapping_sub(b_u) & NUM_MASK,
              MUL => a_u.wrapping_mul(b_u) & NUM_MASK,
              DIV => a_u.wrapping_div(b_u) & NUM_MASK,
              MOD => a_u.wrapping_rem(b_u) & NUM_MASK,
```

It does wrapping (modular) arithmetic on `u128` and then applies the `NUM_MASK` binary mask (biggest u120 possible).
So, it's doing something like `(a + b) % 2^128 % 2^120` — which is hardly practical semantic for anyone.

I think we should document this as undefined behaviour or adopt one of the following options:

1. Runtime error
2. Stuck computation
    - in practice the same as before — the overflown result is always tainted — but easier to detect/visualize
3. Actually wrapping on u120 (might be useful e.g. hashing)

P.S. I actually don't know how cheap high-level signed integers would be implemented without option 3 but I'm too abstract of a being to wrap my head fully around binary operations and stuff

### LINKED ISSUE #162: Division by 0 is not handled
Currently this contract
```
run {
  (/ #3 #0)
}
```
crashes kindelia, because the division operation is done as is (no checks are made):
```
Div => (*a_u).wrapping_div(*b_u) & NUM_MASK
```
and when `b_u` is 0, `wrapping_div` panics and crashes the whole program. This should be treated somehow, but what should be it's intended behaviour? Not reducing? Some kind of runtime error?

cc @steinerkelvin @VictorTaelin

### PR DESCRIPTION
**Pull request by o-santi**
Fixing the semantics of operations on u120 by adding special functions to handle them.

Addition is semantically the same, ie. add as u128 and then chop off at 120 bits.

Subtraction was changed to being addition with the 2's-complement (which i don't think adds enough overhead to care), because messing with the carry bit is messy.

Multiplication was changed to being long-form multiplication, which again I don't think generates that much additional overhead. Honestly I'm not sure if this is the best way to do it, but it works and it is safe.

Division is exactly the same as u128 division, because if both numbers fit in a u120, their quotient also will.

Remainder is also the same.

Shift left and shift right are a bit tricky, because shifting for more bits than the type's width is generally undefined behavior. Because of that, it is defined that the second operand is taken modulo the bit-size (120).

Also added the check to division by 0, and throws DivisionByZero error whenever it would panic.

closes #119
closes #162

### CODE REVIEW

File: src/hvm.rs [hunk 1]
```diff
@@ -982,6 +983,61 @@ impl FromStr for Name {
...
+    let x = (a & LO_MASK) * (b & LO_MASK);
+    
+    let s0 = x & LO_MASK;
+    let x = (a >> 60) * (b & LO_MASK) + (x >> 60);
+    
+    let s1 = x & LO_MASK;
+    let s2 = x >> 60;
+    
+    let x = s2 + (a >> 60) * (b >> 60) + (x >> 60);
+    U120(s1 << 60 | s0)
```
Comment (developedby) [inline src/hvm.rs:1013]: Don't know if more efficient, but I think more readable:
```suggestion
    let a_lo = a & LO_MASK;
    let a_hi = a >> 60;
    let b_lo = b & LO_MASK;
    let b_hi = b >> 60;
    s0 = a_lo * b_lo;
    s1 = ((a_hi * b_lo) & LO_MASK) << 60;
    s2 = ((b_hi * a_lo) & LO_MASK) << 60);
    U120(s0).wrapping_add(U120(s1)).wrapping_add(U120(s2));
```

File: src/hvm.rs [hunk 2]
```diff
@@ -982,6 +983,61 @@ impl FromStr for Name {
...
+  pub fn wrapping_rem(self, other: U120) -> U120 {
+    U120(self.0 % other.0)
+  }
+
+  // Wrapping shift left is only defined for
+  // values `other` between 0 and 127. For values bigger than
+  // that, it will wrap the value module 120 before doing the shift.
+  // Ex: (1u120 << 120) === (1u120 << 0) === 1u120 
+  pub fn wrapping_shl(self, other: U120) -> U120 {
+    U120((self.0 << (other.0 % 120)) & *U120::MAX)
```
Comment (developedby) [inline src/hvm.rs:1035]: Why `.0` in some places and deref in others?

File: src/hvm.rs [hunk 3]
```diff
@@ -982,6 +983,61 @@ impl FromStr for Name {
...
+
+  // Wrapping remainder is just normal remainder
+  // given that self % other is always smaller than other
+  // by definition of the other.
+  pub fn wrapping_rem(self, other: U120) -> U120 {
+    U120(self.0 % other.0)
+  }
+
+  // Wrapping shift left is only defined for
+  // values `other` between 0 and 127. For values bigger than
```
Comment (developedby) [inline src/hvm.rs:1031]:
```suggestion
  // values `other` between 0 and 120. For values bigger than
```

File: src/hvm.rs [hunk 4]
```diff
@@ -982,6 +983,61 @@ impl FromStr for Name {
...
+  // that, it will wrap the value module 120 before doing the shift.
```
Comment (developedby) [inline src/hvm.rs:1032]: Why wrap `other` to 120 instead of shifting `self` to 0 like the normal definition of << and >>?

File: src/test/hvm.rs [hunk 5]
```diff
@@ -440,7 +443,7 @@ proptest! {
 #[case(&format!("(>> #{} #119)", U120::MAX), 1)]
 #[case(&format!("(>> #{} #118)", U120::MAX), 3)]
 #[case(&format!("(+ #{} #1)", U120::MAX), *U120::ZERO)]
-#[case("(- #0 #1)", *U120::MAX)]
```
Comment (developedby) [inline src/test/hvm.rs:443]: I think you meant to add a new case and not erase this one

**Review by developedby — CHANGES_REQUESTED** [review]

File: src/hvm.rs (hunk 2 above)
Comment (o-santi) [reply src/hvm.rs:1035]: Just an oversight, I probably copy pasted some code that was using dereferencing and forgot to change it.

File: src/hvm.rs (hunk 4 above)
Comment (o-santi) [reply src/hvm.rs:1032]: C standard states that it [shifting a number by more than it's width is undefined behaviour](https://wiki.sei.cmu.edu/confluence/display/c/INT34-C.+Do+not+shift+an+expression+by+a+negative+number+of+bits+or+by+greater+than+or+equal+to+the+number+of+bits+that+exist+in+the+operand). The way rust circumvents this is by defining `wrapping_shl`, which will be only defined in that range and the other values are taken modulo the width (javascript does the same thing i think). Based off of that, I implemented the same semantic for shl, and it would be perfectly valid (though less meaningful) to return zero when those cases return. I think it just comes down to our standards and semantics (and I would argue that there's a point doing it like this).

File: src/hvm.rs (hunk 1 above)
Comment (o-santi) [reply src/hvm.rs:1013]: I agree.

File: src/test/hvm.rs (hunk 5 above)
Comment (o-santi) [reply src/test/hvm.rs:443]: Oh! This case was not deleted, just moved it upwards in order to make it a little bit more aligned.

**Review by developedby — APPROVED** [review]

File: src/hvm.rs (hunk 4 above)
Comment (steinerkelvin) [reply src/hvm.rs:1030]: @developedby  The question is: the normal definition?

Comment (developedby) [reply src/hvm.rs:1030]: Normal for me would be to shift into oblivion.
```
0001 << 0 = 0001
0001 << 1 = 0010
0001 << 2 = 0100
0001 << 3 = 1000
0001 << 4 = 0000
```
Same for right shift.

This way, `(a << b) << c = a << (b + c)` which is how i personally intuitively think about it.

Comment (steinerkelvin) [reply src/hvm.rs:1030]: But what language does that?

On C `0001 << 4` is undefined behaviour. On JS `2 << 32 == 2`.

Comment (developedby) [reply src/hvm.rs:1030]: I guess I never actually did that (because why would you)
